### ISSUE TITLE
Cannot run without doing AutoPhrase

### ISSUE THREAD

**Issue by dongheechoi** [dmis-lab/GeNER#2]
* I got error when running below script without running AutoPhrase.
```bash
 python annotate.py --gener_config_path $CONFIG_PATH
```

* Error stack trace
```
Traceback (most recent call last):
  File "annotate.py", line 197, in <module>
    main(args, gener_config)
  File "annotate.py", line 162, in main
    unlabeled_sentences, weak_labels, mined_phrases, abbreviations, raw_dictionary = generate_initial_data(load_path, target_subq)
  File "annotate.py", line 115, in generate_initial_data
    raise FileNotFoundError("Cannot find the '{} file.".format(autophrase_file))
FileNotFoundError: Cannot find the 'Which_***.autophrase file.
```

* Workaround 
    * https://github.com/dmis-lab/GeNER/blob/c73a3d104560001432d5bf8850444ec8ec8f638b/annotate.py#L108
    * I changed the code into below
```python
    # AutoPhrase
    # if target_subq['refine_boundary']:
    #     autophrase_file = '{}.autophrase'.format(target_subq['subquestion'])
    #     if os.path.isfile(os.path.join(load_path, autophrase_file)):
            
    #         with open(os.path.join(load_path, autophrase_file)) as f:
    #             mined_phrases = [l.strip() for l in f.readlines()]
    #     else:
    #         raise FileNotFoundError("Cannot find the '{} file.".format(autophrase_file))
    # else:
    #     mined_phrases = ['' for _ in range(len(examples))]
    mined_phrases = ['' for _ in range(len(examples))]
```

**Comment by nowkim** [comment]
Hi, thanks for this issue! When not applying AutoPhrase, you can comment out the corresponding script as you did. Also, you can simply set "refine_boundary" to false in the configuration file. Please refer to the instruction below!

- https://github.com/dmis-lab/GeNER#autophrase-optional
