### ISSUE TITLE
Cannot run self-training

### ISSUE THREAD

**Issue by dongheechoi** [dmis-lab/GeNER#3]
* I got the below error when trying self-training. 

* error code location
https://github.com/dmis-lab/GeNER/blob/b797b365cbea1a690fcbe5f41801aa1d38a19eb2/self_training/run_self_training_ner.py#L252

* workaround
```python
            # outputs = model(**inputs)
            outputs = model.module(**inputs)
```

* error log

```
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
Cell In[1], line 1
----> 1 outputs = model(**inputs)

File ~/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/modules/module.py:1194, in Module._call_impl(self, *input, **kwargs)
   1190 # If we don't have any hooks, we want to skip the rest of the logic in
   1191 # this function, and just call forward.
   1192 if not (self._backward_hooks or self._forward_hooks or self._forward_pre_hooks or _global_backward_hooks
   1193         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1194     return forward_call(*input, **kwargs)
   1195 # Do not call functions when jit is used
   1196 full_backward_hooks, non_full_backward_hooks = [], []

File ~/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:171, in DataParallel.forward(self, *inputs, **kwargs)
    169     return self.module(*inputs[0], **kwargs[0])
    170 replicas = self.replicate(self.module, self.device_ids[:len(inputs)])
--> 171 outputs = self.parallel_apply(replicas, inputs, kwargs)
    172 return self.gather(outputs, self.output_device)

File ~/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py:181, in DataParallel.parallel_apply(self, replicas, inputs, kwargs)
    180 def parallel_apply(self, replicas, inputs, kwargs):
--> 181     return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])

File ~/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py:89, in parallel_apply(modules, inputs, kwargs_tup, devices)
     87     output = results[i]
     88     if isinstance(output, ExceptionWrapper):
---> 89         output.reraise()
     90     outputs.append(output)
     91 return outputs

File ~/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/_utils.py:543, in ExceptionWrapper.reraise(self)
    539 except TypeError:
    540     # If the exception takes multiple arguments, don't try to
    541     # instantiate since we don't know how to
    542     raise RuntimeError(msg) from None
--> 543 raise exception

StopIteration: Caught StopIteration in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/projects/GeNER/self_training/modeling_roberta.py", line 66, in forward
    outputs = self.roberta(
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/transformers/modeling_bert.py", line 707, in forward
    attention_mask, input_shape, self.device
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/transformers/modeling_utils.py", line 113, in device
    return next(self.parameters()).device
StopIteration
```

**Comment by dongheechoi** [comment]
* workaround still has an error, so I just put device variable to makefile.
```
self-training:
	CUDA_DEVICE_ORDER=PCI_BUS_ID CUDA_VISIBLE_DEVICES=0 python3
```

* error log
```
Traceback (most recent call last):
  File "./self_training/run_self_training_ner.py", line 746, in <module>
    main()
  File "./self_training/run_self_training_ner.py", line 679, in main
    model, global_step, tr_loss, best_dev, best_test = train(args, train_dataset, model_class, config, tokenizer, labels, pad_token_label_id)
  File "./self_training/run_self_training_ner.py", line 233, in train
    outputs = self_training_teacher_model(**inputs)
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 171, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 181, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 89, in parallel_apply
    output.reraise()
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/_utils.py", line 543, in reraise
    raise exception
StopIteration: Caught StopIteration in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/parallel/parallel_apply.py", line 64, in _worker
    output = module(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/projects/GeNER/self_training/modeling_roberta.py", line 66, in forward
    outputs = self.roberta(
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/transformers/modeling_bert.py", line 707, in forward
    attention_mask, input_shape, self.device
  File "/home/ubuntu/anaconda3/envs/GeNER/lib/python3.8/site-packages/transformers/modeling_utils.py", line 113, in device
    return next(self.parameters()).device
StopIteration
```

**Comment by nowkim** [comment]
Hi, thank you for this issue! You should set `export CUDA_VISIBLE_DEVICES={device id}` before running the model on GPU.
